---

- name: Install dovecot
  pkgng:
    name: "{{ dovecot_package }}"
    state: present

- name: Create /etc/rc.conf.d/dovecot
  template:
    src: FreeBSD.rcd.j2
    dest: "/etc/rc.conf.d/{{ dovecot_service }}"
