---

- name: Install dovecot
  openbsd_pkg:
    name: "{{ dovecot_package }}"
    state: present

- name: Enable dovecot
  service:
    name: "{{ dovecot_service }}"
    arguments: "{{ dovecot_flags }}"
    enabled: yes

- name: Install additional dovecot packages
  openbsd_pkg:
    name: "{{ item }}"
    state: present
  with_items: "{{ dovecot_extra_packages }}"

- name: Create login.conf(5) entry for dovecot user
  # see /usr/local/share/doc/pkg-readmes/dovecot-*
  blockinfile:
    path: /etc/login.conf
    block: "{{ dovecot_login_class }}"
