---

- name: Install dovecot
  pkgng:
    name: "{{ dovecot_package }}"
    state: present

- name: Patch /usr/local/etc/rc.d/dovecot
  patch:
    src: FreeBSD.rc.patch
    dest: /usr/local/etc/rc.d/dovecot
    state: present

- name: Install additional dovecot packages
  pkgng:
    name: "{{ dovecot_extra_packages }}"
    state: present

- name: Create /etc/rc.conf.d/dovecot
  template:
    src: FreeBSD.rcd.j2
    dest: "/etc/rc.conf.d/{{ dovecot_service }}"
    validate: sh -n %s

- name: Enable dovecot
  service:
    name: "{{ dovecot_service }}"
    enabled: yes
